#!/bin/sh

# This is a FAKE ggsci shell for testing

script_dir=$(cd $(dirname $0);pwd)

read -p "wait for command:" cmd
if [ "$cmd" == "info all" ]
then
  cat $script_dir/infoall.log
elif [ "$cmd" == "info * detail" ]
then
  cat $script_dir/infodetail.log
else
  echo "ggsci error input: $cmd"
fi
