project_name: cthun
release:
  github:
    owner: frank3950
    name: cthun
  name_template: '{{.Tag}}'
builds:
- id: cthun
  goos:
  - linux
  goarch:
  - amd64
  goarm:
  - "6"
  gomips:
  - hardfloat
  targets:
  - linux_amd64
  dir: .
  main: ./cmd/
  ldflags:
  - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    -X main.builtBy=goreleaser
  binary: cthun
  builder: go
  gobinary: go
archives:
- id: default
  builds:
  - cthun
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
  format: tar.gz
  files:
  - src: license*
  - src: LICENSE*
  - src: readme*
  - src: README*
  - src: changelog*
  - src: CHANGELOG*
snapshot:
  name_template: '{{ .Version }}-SNAPSHOT-{{ .ShortCommit }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha256
dist: dist
env_files:
  github_token: ~/.config/goreleaser/github_token
  gitlab_token: ~/.config/goreleaser/gitlab_token
  gitea_token: ~/.config/goreleaser/gitea_token
source:
  name_template: '{{ .ProjectName }}-{{ .Version }}'
  format: tar.gz
gomod:
  gobinary: go
github_urls:
  download: https://github.com
gitlab_urls:
  download: https://gitlab.com