name: Test
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  Test:
    runs-on: ubuntu-latest
    container:
      image: "centos:7"
    steps:
    - run: yum install -y gcc
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: chmod +x test/ggsci
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.txt